final merge develop to master
PSMRI/ECD-UI pull request #3
Opened 2024-08-02 09:48 UTC by NKOKKILIGADDA87

2024-08-02 09:53 UTC, drtechie requested changes
Please remove references to -next
@pavangsk please ensure this is applied to all UI repos.

Add proper description for the PR.

2024-08-02 09:54 UTC, drtechie commented on src/environments/environment.ci.ts.template
> +downloadCumulativeReportURL:`${ECD_API}ecdReportController/getECDCumulativeDistrictReport`,
Indent is off on this file

2024-08-02 10:17 UTC, pavangsk commented
> Please remove references to -next @pavangsk please ensure this is applied to all UI repos.
> 
> Add proper description for the PR.

2024-08-02 10:18 UTC, pavangsk commented
Hi @drtechie Informed team to remove -next in all repositories, Team will update the changes and raise new PR to Main branch.

2024-08-12 14:31 UTC, helenKaryamsetty reviewed
THere are merge conflicts in this PR please resolve those

2024-08-13 07:38 UTC, merged